### ISSUE TITLE
Create-react-app tutorial page: outdated dependencies

### ISSUE THREAD

**Issue by alechp** [graphcool/content#171] opened 2017-06-14 19:33 UTC
Tutorial in question: [How to use `create-react-app` with GraphQL & Apollo](https://www.graph.cool/docs/tutorials/create-react-apps-with-apollo-client-aidae4aeg5/)

**Issue 1:** browserHistory from react-router no longer available

**Issue origin:**
<img width="755" alt="screen shot 2017-06-14 at 9 41 47 am" src="https://user-images.githubusercontent.com/3058939/27150914-cb5d61fc-50fd-11e7-8506-c97f7adba9f3.png">

**Relevant react-router docs:**
[Can no longer import { IndexRoute, browserHistory } from version 4. · Issue #4732 · ReactTraining/react-router · GitHub](https://github.com/ReactTraining/react-router/issues/4732)

**Issue 2** Import gql from ‘react-apollo’ instead of manually importing from graphql-tag

**Issue origin:**
<img width="779" alt="screen shot 2017-06-14 at 9 42 25 am" src="https://user-images.githubusercontent.com/3058939/27150919-cea11a8e-50fd-11e7-92fc-7db6fc2279b6.png">

**Relevant React Apollo docs:**
http://dev.apollodata.com/react/queries.html

**Comment by marktani** [comment] 2017-07-18 15:36
Thanks for the report! Closed as duplicate of #56 and #94.

**Closed by marktani** 2017-07-18 15:36 UTC
Labels: adjustment, type/tutorial
