### ISSUE TITLE
graphql-tag now with react-apollo

### ISSUE THREAD

**Issue by joaobsantos** [graphcool/content#40] opened 2017-04-06 17:25 UTC
Now you can use, import { graphql, gql } from 'react-apollo'.
There's no need to install graphql-tag dependency.

**Old way:**
import { graphql } from 'react-apollo'
import { gql } from 'graphql-tag'

**New way:**
import { graphql, gql } from 'react-apollo'

**Comment by schickling** [comment] 2017-04-13 13:08
@marktani can you go through all resources where we've used `graphql-tag` and remove it?

**Comment by marktani** [comment] 2017-05-25 15:35
removed as duplicate of #56

**Closed by marktani** 2017-05-25 15:35 UTC
Labels: adjustment, feedback
